services:
  - type: web
    name: flashmail-backend
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard
      - key: EMAIL_DOMAIN
        value: flashmail.onrender.com
      - key: EMAIL_EXPIRATION_HOURS
        value: "24"
      - key: PORT
        value: "3001"
      - key: SMTP_PORT
        value: "2525"
    healthCheckPath: /health
    autoDeploy: true

  - type: static
    name: flashmail-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://flashmail-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    routes:
      - type: rewrite
        source: /*
        destination: /index.html