services:
  - type: web
    name: flashmail-backend
    env: node
    buildCommand: |
      echo "Installing backend dependencies..."
      cd server
      npm install
      echo "Building backend..."
      npm run build
      echo "Backend build completed"
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard
      - key: EMAIL_DOMAIN
        value: flashmail.onrender.com
      - key: EMAIL_EXPIRATION_HOURS
        value: "24"
      - key: PORT
        value: "3001"
      - key: SMTP_PORT
        value: "2525"
    healthCheckPath: /health
    autoDeploy: true
    # Note: Render automatically exposes the PORT environment variable
    # SMTP port will be handled by the application internally

  - type: web
    name: flashmail-frontend
    env: static
    buildCommand: |
      echo "Current directory:"
      pwd
      echo "Installing frontend dependencies..."
      cd client
      echo "Installing dependencies..."
      npm install --legacy-peer-deps
      echo "Building frontend..."
      DISABLE_ESLINT_PLUGIN=true CI=false npm run build
      echo "Build directory contents:"
      ls -la build/
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://flashmail-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    routes:
      - type: rewrite
        source: /*
        destination: /index.html